version: '3.9'

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: sensor_data

  # Machine Learning Client Service
  ml-client:
    build: ./machine-learning-client
    container_name: ml-client
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./machine-learning-client:/app
    environment:
      - MONGO_URI=mongodb://mongodb:27017/sensor_data
      - FLASK_PORT=5000
    command: ["python", "main.py"]

  # Web App Service
  web-app:
    build: ./web-app
    container_name: web-app
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./web-app:/app
    ports:
      - "8000:8000"  
    environment:
      - MONGO_URI=mongodb://mongodb:27017/sensor_data
      - FLASK_PORT=5001
    command: ["python", "app.py"]
    env_file:
      - .env

volumes:
  mongodb_data:
    driver: local
